# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='role_category',
            field=models.PositiveIntegerField(choices=[(1, b'Ajab Capital User'), (2, b'Loan Partner User'), (3, b'Loan Client User')]),
        ),
        migrations.AlterField(
            model_name='rolecapability',
            name='role_code',
            field=models.PositiveIntegerField(choices=[(1, b'Super Admin'), (2, b'Ajab Capital Staff'), (3, b'Loan Administrator'), (4, b'Loan Officer'), (5, b'Loan Client')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, b'Super Admin'), (2, b'Ajab Capital Staff'), (3, b'Loan Administrator'), (4, b'Loan Officer'), (5, b'Loan Client')]),
        ),
    ]
