# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_performing', models.BooleanField()),
                ('is_guarantor', models.BooleanField(default=False)),
                ('has_fraud', models.BooleanField(default=False)),
                ('has_current_delinquency', models.BooleanField()),
                ('has_historical_delinquency', models.BooleanField()),
                ('total_no_of_applications', models.PositiveIntegerField()),
                ('min_days_in_arrears', models.PositiveIntegerField()),
                ('max_days_in_arrears', models.PositiveIntegerField()),
                ('total_current_credit_exposure', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_riskprofile_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_riskprofile_deleted_by_me', to=settings.AUTH_USER_MODEL)),
                ('loan_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='loan.LoanProfile')),
                ('worst_risk_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigLoanRiskClassification')),
            ],
            options={
                'db_table': 'risk_profile',
                'verbose_name': 'Risk Profile',
            },
        ),
    ]
