# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 09:29
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk_management', '0001_initial'),
    ]

    operations = [
    ]
