# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0002_auto_20160219_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configloanriskclassification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configloanriskclassification',
            name='deleted_by',
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='worst_risk_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigLoanRiskClassification'),
        ),
        migrations.DeleteModel(
            name='ConfigLoanRiskClassification',
        ),
    ]
