# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0004_auto_20160220_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='configidentitytype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
