# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 09:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk_management', '0004_auto_20160426_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileRiskClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=140, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals_on_loan_risk_status', to=settings.AUTH_USER_MODEL)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='risk_management.ConfigLoanRiskClassification')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_profileriskclassification_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_profileriskclassification_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_profile_risk_classification',
                'verbose_name': 'Risk Profile Risk Classification',
                'verbose_name_plural': 'Risk Profile Risk Classifications',
            },
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='current_risk_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classified_loans', related_query_name='classified_loan', to='risk_management.ConfigLoanRiskClassification'),
        ),
        migrations.AddField(
            model_name='profileriskclassification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_classifications', to='risk_management.RiskProfile'),
        ),
    ]
