# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0005_configidentitytype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='configidentitytype',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
    ]
