# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0005_auto_20160426_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileriskclassification',
            options={'verbose_name': 'Risk Profile Risk Classification'},
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='current_risk_classification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='profileriskclassification',
            table='risk_profile_risk_status',
        ),
    ]
