# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0006_auto_20160426_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='configloanriskclassification',
            name='color',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
