# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0006_configidentitytype_system_defined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configidentitytype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configidentitytype',
            name='deleted_by',
        ),
        migrations.RenameField(
            model_name='riskprofile',
            old_name='no_of_applications',
            new_name='total_no_of_applications',
        ),
        migrations.RemoveField(
            model_name='riskprofile',
            name='identity_number',
        ),
        migrations.RemoveField(
            model_name='riskprofile',
            name='identity_type',
        ),
        migrations.DeleteModel(
            name='ConfigIdentityType',
        ),
    ]
