# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 14:30
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(max_length=30)),
                ('date_opened', models.DateTimeField(blank=True, null=True)),
                ('original_amount', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=25)),
                ('current_balance', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=25)),
                ('overdue_balance', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=25)),
                ('last_payment_amount', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=25)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('days_in_arrears', models.IntegerField(blank=True, null=True)),
                ('overdue_date', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.CharField(max_length=100)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column=b'created_by', on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_metropol_accountsearchresult_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column=b'deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_metropol_accountsearchresult_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metropol_account_search_result',
                'verbose_name': 'Metropol Account Search Result',
            },
        ),
        migrations.CreateModel(
            name='ConfigMetropolDelinquencyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_by', models.ForeignKey(db_column=b'created_by', on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_metropol_configmetropoldelinquencycode_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column=b'deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_metropol_configmetropoldelinquencycode_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_metropol_delinquency_code',
                'verbose_name': 'Config Metropol Delinquency Code',
            },
        ),
        migrations.CreateModel(
            name='ConfigMetropolProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_by', models.ForeignKey(db_column=b'created_by', on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_metropol_configmetropolproducttype_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column=b'deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_metropol_configmetropolproducttype_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_metropol_product_type',
                'verbose_name': 'Config Metropol Product Type',
            },
        ),
        migrations.CreateModel(
            name='MetropolIdentitySearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_canceled', models.BooleanField(default=False)),
                ('date_canceled', models.DateTimeField(blank=True, null=True)),
                ('cancel_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('search_ref_number', models.CharField(max_length=10, unique=True)),
                ('created_by', models.ForeignKey(db_column=b'created_by', on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_metropol_metropolidentitysearch_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column=b'deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_metropol_metropolidentitysearch_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metropol_identity_search',
                'verbose_name': 'Metropol Identity Search',
                'verbose_name_plural': 'Metropol Identity Searches',
            },
        ),
        migrations.CreateModel(
            name='MetropolIdentitySearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_ref_code', models.CharField(max_length=100)),
                ('is_guarantor', models.BooleanField(default=False)),
                ('has_fraud', models.BooleanField(default=False)),
                ('credit_score', models.IntegerField(null=True)),
                ('credit_app_12', models.IntegerField(default=0, null=True)),
                ('credit_app_6', models.IntegerField(default=0, null=True)),
                ('credit_app_3', models.IntegerField(default=0, null=True)),
                ('enquiries_12', models.IntegerField(default=0, null=True)),
                ('enquiries_6', models.IntegerField(default=0, null=True)),
                ('enquiries_3', models.IntegerField(default=0, null=True)),
                ('bounced_cheques_12', models.IntegerField(default=0, null=True)),
                ('bounced_cheques_6', models.IntegerField(default=0, null=True)),
                ('bounced_cheques_3', models.IntegerField(default=0, null=True)),
                ('created_by', models.ForeignKey(db_column=b'created_by', on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_metropol_metropolidentitysearchresult_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column=b'deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_metropol_metropolidentitysearchresult_deleted_by_me', to=settings.AUTH_USER_MODEL)),
                ('delinquency_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_management_metropol.ConfigMetropolDelinquencyCode')),
                ('search', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='risk_management_metropol.MetropolIdentitySearch')),
            ],
            options={
                'db_table': 'metropol_identity_search_result',
                'verbose_name': 'Metropol Identity Search Result',
            },
        ),
        migrations.CreateModel(
            name='MetropolRiskProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column=b'created_by', on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_metropol_metropolriskprofile_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column=b'deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_metropol_metropolriskprofile_deleted_by_me', to=settings.AUTH_USER_MODEL)),
                ('risk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_management.RiskProfile')),
            ],
            options={
                'db_table': 'metropol_risk_profile',
                'verbose_name': 'Metropol Risk Profile',
            },
        ),
        migrations.AddField(
            model_name='metropolidentitysearch',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_management_metropol.MetropolRiskProfile'),
        ),
        migrations.AddField(
            model_name='accountsearchresult',
            name='delinquency_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_management_metropol.ConfigMetropolDelinquencyCode'),
        ),
        migrations.AddField(
            model_name='accountsearchresult',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_management_metropol.ConfigMetropolProductType'),
        ),
        migrations.AddField(
            model_name='accountsearchresult',
            name='search_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_management_metropol.MetropolIdentitySearchResult'),
        ),
    ]
