# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management_metropol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmetropoldelinquencycode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configmetropolproducttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
