# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management_metropol', '0002_auto_20160221_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmetropoldelinquencycode',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configmetropolproducttype',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
    ]
