# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='business_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_messages', to='crm.BusinessProfile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='group_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='crm.GroupProfile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='individual_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_messages', to='crm.IndividualProfile'),
        ),
    ]
