# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20160218_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confignotificationtrigger',
            options={'verbose_name': 'Config Notification Trigger'},
        ),
    ]
