# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20160219_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'Customer Profile'},
        ),
    ]
