# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20160219_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='confignotificationaction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='confignotificationschedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='confignotificationstatus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='confignotificationtrigger',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='confignotificationtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
