# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20160221_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='confignotificationaction',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confignotificationschedule',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confignotificationstatus',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confignotificationtrigger',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confignotificationtype',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
    ]
