# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 01:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0058_auto_20160323_0132'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0009_auto_20160323_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigLoanGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_defined', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'config_loan_group_type',
                'verbose_name': 'Config Loan Group Status',
                'verbose_name_plural': 'Config Loan Group Statuses',
            },
        ),
        migrations.CreateModel(
            name='ConfigLoanGroupRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_defined', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'config_loan_group_role',
                'verbose_name': 'Config Loan Group Role',
            },
        ),
        migrations.CreateModel(
            name='ConfigLoanGroupStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_defined', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'config_loan_group_status',
                'verbose_name': 'Config Loan Group Status',
                'verbose_name_plural': 'Config Loan Group Statuses',
            },
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
        migrations.DeleteModel(
            name='Segment',
        ),
        migrations.AddField(
            model_name='profiledocumentupload',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profiledocumentupload',
            name='business_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.BusinessProfile'),
        ),
        migrations.AddField(
            model_name='profiledocumentupload',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_profiledocumentupload_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profiledocumentupload',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_profiledocumentupload_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profiledocumentupload',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ConfigDocumentType'),
        ),
        migrations.AddField(
            model_name='profiledocumentupload',
            name='group_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.GroupProfile'),
        ),
        migrations.AddField(
            model_name='profiledocumentupload',
            name='individual_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.IndividualProfile'),
        ),
        migrations.AddField(
            model_name='profiledocumentupload',
            name='upload_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ConfigMessageAction'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_messagetemplate_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_messagetemplate_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='business_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_messages', to='crm.BusinessProfile'),
        ),
        migrations.AddField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_message_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_message_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='group_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='crm.GroupProfile'),
        ),
        migrations.AddField(
            model_name='message',
            name='individual_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_messages', to='crm.IndividualProfile'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ConfigMessageType'),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ConfigMessageStatus'),
        ),
        migrations.AddField(
            model_name='message',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.MessageTemplate'),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_individualprofile_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_individualprofile_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='identity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ConfigIdentityType'),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupprofilestatus',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupprofilestatus',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_groupprofilestatus_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupprofilestatus',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_groupprofilestatus_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupprofilestatus',
            name='group_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.GroupProfile'),
        ),
        migrations.AddField(
            model_name='groupprofilestatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ConfigGroupProfileStatus'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_groupprofile_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_groupprofile_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='last_group_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ConfigLoanGroupStatus'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='loan_group_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.ConfigLoanGroupType'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='business_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_members', to='crm.BusinessProfile'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_groupmembership_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_groupmembership_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='crm.GroupProfile'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ConfigLoanGroupRole'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='individual_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_members', to='crm.IndividualProfile'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='loan_group_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crm.GroupProfile'),
        ),
        migrations.AddField(
            model_name='configmessagetype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_configmessagetype_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configmessagetype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_configmessagetype_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configmessagestatus',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_configmessagestatus_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configmessagestatus',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_configmessagestatus_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configmessageaction',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_configmessageaction_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configmessageaction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_configmessageaction_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configloangrouptype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_configloangrouptype_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configloangrouptype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_configloangrouptype_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configloangroupstatus',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_configloangroupstatus_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configloangroupstatus',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_configloangroupstatus_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configloangrouprole',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_configloangrouprole_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configloangrouprole',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_configloangrouprole_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configgroupprofilestatus',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_configgroupprofilestatus_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configgroupprofilestatus',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_configgroupprofilestatus_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configdocumenttype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_configdocumenttype_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configdocumenttype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_configdocumenttype_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configcampaignsegmenttype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_configcampaignsegmenttype_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configcampaignsegmenttype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_configcampaignsegmenttype_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configbusinesstype',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_configbusinesstype_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configbusinesstype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_configbusinesstype_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configbusinessrole',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_configbusinessrole_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configbusinessrole',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_configbusinessrole_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessstakeholder',
            name='business_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_stakeholder', to='crm.BusinessProfile'),
        ),
        migrations.AddField(
            model_name='businessstakeholder',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_businessstakeholder_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessstakeholder',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_businessstakeholder_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessstakeholder',
            name='group_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_stakeholder', to='crm.GroupProfile'),
        ),
        migrations.AddField(
            model_name='businessstakeholder',
            name='individual_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_stakeholder', to='crm.IndividualProfile'),
        ),
        migrations.AddField(
            model_name='businessstakeholder',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ConfigBusinessRole'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_businessprofile_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_businessprofile_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='identity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ConfigIdentityType'),
        ),
        migrations.AlterUniqueTogether(
            name='profiledocumentupload',
            unique_together=set([('file_upload_reference_number', 'batch_upload_reference_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='individualprofile',
            unique_together=set([('identity_number', 'identity_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='businessprofile',
            unique_together=set([('identity_number', 'identity_type')]),
        ),
    ]
