# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0011_auto_20160323_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfileStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_profile_status',
                'verbose_name': 'Business Profile Status',
            },
        ),
        migrations.CreateModel(
            name='ConfigBusinessProfileStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_defined', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_configbusinessprofilestatus_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_configbusinessprofilestatus_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_business_profile_status',
                'verbose_name': 'Config Business Profile Status',
            },
        ),
        migrations.RenameField(
            model_name='businessstakeholder',
            old_name='group_profile',
            new_name='stakeholding_group',
        ),
        migrations.RenameField(
            model_name='businessstakeholder',
            old_name='individual_profile',
            new_name='stakeholding_individual',
        ),
        migrations.RenameField(
            model_name='groupmembership',
            old_name='business_profile',
            new_name='member_business',
        ),
        migrations.RenameField(
            model_name='groupmembership',
            old_name='group_profile',
            new_name='member_group',
        ),
        migrations.RenameField(
            model_name='groupmembership',
            old_name='individual_profile',
            new_name='member_individual',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='name',
            field=models.CharField(default='N', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessstakeholder',
            name='stakeholding_business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_stakeholder', to='crm.BusinessProfile'),
        ),
        migrations.AlterField(
            model_name='businessstakeholder',
            name='business_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='crm.BusinessProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprofilestatus',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.BusinessProfile'),
        ),
        migrations.AddField(
            model_name='businessprofilestatus',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='crm_businessprofilestatus_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessprofilestatus',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_businessprofilestatus_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessprofilestatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ConfigBusinessProfileStatus'),
        ),
    ]
