# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20160323_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='last_repayment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='last_repayment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='last_repayment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
