# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 13:21
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20160323_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='first_disbursal_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='last_disbursal_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='first_disbursal_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='last_disbursal_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='first_disbursal_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='last_disbursal_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
    ]
