# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20160323_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualprofile',
            name='is_active',
        ),
    ]
