# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_remove_individualprofile_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessstakeholder',
            options={'verbose_name': 'Business Stakeholder'},
        ),
        migrations.AlterModelOptions(
            name='groupprofilestatus',
            options={'verbose_name': 'Group Profile Status'},
        ),
        migrations.AlterModelOptions(
            name='individualprofile',
            options={'verbose_name': 'Individual Profile'},
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='code',
        ),
    ]
