# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20160323_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprofile',
            name='profile_type',
            field=models.PositiveIntegerField(choices=[(1, 'Client'), (2, 'Group Member'), (3, 'Business Stakeholder')], default=1),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='gender',
            field=models.PositiveIntegerField(choices=[(0, 'Female'), (1, 'Male')]),
        ),
    ]
