# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20160323_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='last_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ConfigBusinessProfileStatus'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='last_status_date',
            field=models.DateTimeField(null=True),
        ),
    ]
