# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 14:19
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBlockType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_defined', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'config_block_type',
                'verbose_name': 'Config Block Type',
            },
        ),
        migrations.CreateModel(
            name='ConfigCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_defined', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'config_currency',
                'verbose_name': 'Config Currency',
                'verbose_name_plural': 'Config Currencies',
            },
        ),
        migrations.CreateModel(
            name='ConfigLedgerAccountBalanceDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_defined', models.BooleanField(default=False)),
                ('icon', models.FileField(blank=True, null=True, upload_to=b'config/icons/')),
            ],
            options={
                'db_table': 'config_ledger_account_balance_direction',
                'verbose_name': 'Config Ledger Balance Direction',
            },
        ),
        migrations.CreateModel(
            name='ConfigLedgerAccountCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_defined', models.BooleanField(default=False)),
                ('icon', models.FileField(blank=True, null=True, upload_to=b'config/icons/')),
            ],
            options={
                'db_table': 'config_ledger_account_category',
                'verbose_name': 'Config Ledger Account Category',
                'verbose_name_plural': 'Config Ledger Account Categories',
            },
        ),
        migrations.CreateModel(
            name='ConfigLedgerTransactionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_defined', models.BooleanField(default=False)),
                ('icon', models.FileField(blank=True, null=True, upload_to=b'config/icons/')),
            ],
            options={
                'db_table': 'config_ledger_transaction_status',
                'verbose_name': 'Config Ledger Transaction Status',
                'verbose_name_plural': 'Config Ledger Transaction Statuses',
            },
        ),
        migrations.CreateModel(
            name='ConfigLedgerTransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_defined', models.BooleanField(default=False)),
                ('icon', models.FileField(blank=True, null=True, upload_to=b'config/icons/')),
                ('posts_to_ledger', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'config_ledger_transaction_type',
                'verbose_name': 'Config Ledger Transaction Type',
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ledger_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('system_defined', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ledger_account',
                'verbose_name': 'Ledger Account',
            },
        ),
        migrations.CreateModel(
            name='LedgerAccountingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_defined', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ledger_accounting_rule',
                'verbose_name': 'Ledger Accounting Rule',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_account', models.CharField(max_length=25, null=True)),
                ('ledger_balance_item_type', models.PositiveIntegerField(choices=[(0, b'Debit'), (1, b'Credit')])),
                ('ledger_balance_increment', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
            ],
            options={
                'db_table': 'ledger_entry',
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('product_type', models.PositiveIntegerField(choices=[(1, b'Loan'), (2, b'Savings')])),
                ('product_account', models.CharField(max_length=25, null=True)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18)),
                ('notes', models.CharField(max_length=500, null=True)),
                ('notified', models.NullBooleanField()),
                ('last_status_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'ledger_transaction',
                'verbose_name': 'Ledger Transaction',
            },
        ),
        migrations.CreateModel(
            name='LedgerTransactionBlock',
            fields=[
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=160)),
                ('balances_as_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ledger_transaction_block',
                'verbose_name': 'Ledger Transaction Block',
            },
        ),
        migrations.CreateModel(
            name='LedgerTransactionBlockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18)),
                ('product_type', models.PositiveIntegerField(choices=[(1, b'Loan'), (2, b'Savings')], default=1)),
                ('product_account', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ledger_transaction_block_item',
                'verbose_name': 'Ledger Transaction Block Item',
            },
        ),
        migrations.CreateModel(
            name='LedgerTransactionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_status_date', models.DateTimeField()),
                ('notes', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'ledger_transaction_status',
                'verbose_name': 'Ledger Transaction Status',
                'verbose_name_plural': 'Ledger Transaction Statuses',
            },
        ),
    ]
