# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160421_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgeraccount',
            options={'ordering': ['ledger_code'], 'verbose_name': 'Ledger Account'},
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
