# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160425_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgertransaction',
            name='product_type',
            field=models.PositiveIntegerField(choices=[(1, b'Loan'), (2, b'Savings')], null=True),
        ),
    ]
