# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160222_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgerbalanceregister',
            old_name='closure_type',
            new_name='balance_closure_type',
        ),
        migrations.AddField(
            model_name='configledgeraccounttype',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='config/icons/'),
        ),
        migrations.AddField(
            model_name='configledgertransactiontype',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='config/icons/'),
        ),
    ]
