# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160222_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='configledgeraccountcategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='config/icons/'),
        ),
    ]
