# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160222_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'verbose_name': 'Ledger Entry', 'verbose_name_plural': 'Ledger Entries'},
        ),
        migrations.RemoveField(
            model_name='ledgertransaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='transaction_no',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
