# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20160222_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerTransactionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='core_ledgertransactionstatus_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_ledgertransactionstatus_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ledger_transaction_status',
                'verbose_name': 'Ledger Transaction Status',
                'verbose_name_plural': 'Ledger Transaction Statuses',
            },
        ),
        migrations.RemoveField(
            model_name='ledgertransaction',
            name='transaction_status',
        ),
        migrations.AddField(
            model_name='ledgertransactionstatus',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LedgerTransaction'),
        ),
        migrations.AddField(
            model_name='ledgertransactionstatus',
            name='transaction_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ConfigLedgerTransactionStatus'),
        ),
    ]
