# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 20:14
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20160222_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceClosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=160)),
                ('balance_as_at', models.DateTimeField()),
                ('balance_closure_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ConfigBalanceClosureType')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='core_balanceclosure_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_balanceclosure_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'balance_closure',
                'verbose_name': 'Ledger Balance Register',
                'verbose_name_plural': 'Ledger Balance Register',
            },
        ),
        migrations.CreateModel(
            name='BalanceClosureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='core_balanceclosureitem_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_balanceclosureitem_deleted_by_me', to=settings.AUTH_USER_MODEL)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LedgerAccount')),
            ],
            options={
                'db_table': 'balance_closure_item',
                'verbose_name': 'Balance Closure Item',
                'verbose_name_plural': 'Balance Closure Item',
            },
        ),
        migrations.RemoveField(
            model_name='ledgerbalanceregister',
            name='balance_closure_type',
        ),
        migrations.RemoveField(
            model_name='ledgerbalanceregister',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ledgerbalanceregister',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='ledgerbalanceregister',
            name='ledger_account',
        ),
        migrations.DeleteModel(
            name='LedgerBalanceRegister',
        ),
    ]
