# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 22:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20160223_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigLedgerAccountBalanceDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='config/icons/')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='core_configledgeraccountbalancedirection_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_configledgeraccountbalancedirection_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_ledger_account_balance_direction',
                'verbose_name': 'Config Ledger Balance Direction',
            },
        ),
        migrations.RenameField(
            model_name='balanceclosure',
            old_name='balance_as_at',
            new_name='balances_as_at',
        ),
        migrations.AddField(
            model_name='balanceclosureitem',
            name='balance_closure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.BalanceClosure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledgertransactionstatus',
            name='transaction_status_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 23, 22, 58, 46, 235632, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ledgertransactionstatus',
            name='transaction_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core.ConfigLedgerTransactionStatus'),
        ),
    ]
