# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160223_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='balance_direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ConfigLedgerAccountBalanceDirection'),
            preserve_default=False,
        ),
    ]
