# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 07:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_ledgeraccount_balance_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccountingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='core_ledgeraccountingrule_created_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ledger_accounting_rule',
                'verbose_name': 'Ledger Accounting Rules',
            },
        ),
        migrations.AlterModelOptions(
            name='balanceclosure',
            options={'verbose_name': 'Balance Closure', 'verbose_name_plural': 'Balance Closure'},
        ),
        migrations.AlterField(
            model_name='balanceclosureitem',
            name='ledger_account',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='ledger_code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='ledger_account',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='ledger_balance_item_type',
            field=models.PositiveIntegerField(choices=[(1, 'Debit'), (0, 'Credit')]),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='ledger_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enties', to='core.LedgerTransaction'),
        ),
        migrations.AddField(
            model_name='ledgeraccountingrule',
            name='credit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.LedgerAccount'),
        ),
        migrations.AddField(
            model_name='ledgeraccountingrule',
            name='debit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='core.LedgerAccount'),
        ),
        migrations.AddField(
            model_name='ledgeraccountingrule',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_ledgeraccountingrule_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgeraccountingrule',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_rules', to='core.ConfigLedgerTransactionType'),
        ),
    ]
