# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160226_0718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgeraccountingrule',
            options={'verbose_name': 'Ledger Accounting Rule'},
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='product_account',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LedgerAccount'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='ledger_balance_item_type',
            field=models.PositiveIntegerField(choices=[(0, 'Debit'), (1, 'Credit')]),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='notified',
            field=models.NullBooleanField(),
        ),
    ]
