# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 07:43
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20160228_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBlockType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='core_configblocktype_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_configblocktype_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_block_type',
                'verbose_name': 'Config Block Type',
            },
        ),
        migrations.CreateModel(
            name='LedgerProductBlockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_account', models.CharField(max_length=25)),
                ('balance_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18)),
            ],
            options={
                'db_table': 'product_account_block_item',
                'verbose_name': 'Ledger Product Block Item',
            },
        ),
        migrations.CreateModel(
            name='LedgerTransactionBlock',
            fields=[
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=160)),
                ('balances_as_at', models.DateTimeField()),
                ('block_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ConfigBlockType')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='core_ledgertransactionblock_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_ledgertransactionblock_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ledger_transaction_block',
                'verbose_name': 'Ledger Transaction Block',
            },
        ),
        migrations.CreateModel(
            name='LedgerTransactionBlockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_items', to='core.LedgerTransactionBlock')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='core_ledgertransactionblockitem_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_ledgertransactionblockitem_deleted_by_me', to=settings.AUTH_USER_MODEL)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LedgerAccount')),
            ],
            options={
                'db_table': 'ledger_transaction_block_item',
                'verbose_name': 'Ledger Transaction Block Item',
            },
        ),
        migrations.RemoveField(
            model_name='balanceclosure',
            name='balance_closure_type',
        ),
        migrations.RemoveField(
            model_name='balanceclosure',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='balanceclosure',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='balanceclosureitem',
            name='balance_closure',
        ),
        migrations.RemoveField(
            model_name='balanceclosureitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='balanceclosureitem',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='configbalanceclosuretype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configbalanceclosuretype',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='last_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.LedgerTransactionStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='last_status_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 29, 7, 43, 30, 587772, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='product_account',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='ledgertransactionstatus',
            name='notes',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BalanceClosure',
        ),
        migrations.DeleteModel(
            name='BalanceClosureItem',
        ),
        migrations.DeleteModel(
            name='ConfigBalanceClosureType',
        ),
        migrations.AddField(
            model_name='ledgerproductblockitem',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_block_items', to='core.LedgerTransactionBlock'),
        ),
        migrations.AddField(
            model_name='ledgerproductblockitem',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='core_ledgerproductblockitem_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerproductblockitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_ledgerproductblockitem_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
