# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160229_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerproductblockitem',
            name='block',
        ),
        migrations.RemoveField(
            model_name='ledgerproductblockitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ledgerproductblockitem',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='ledgertransactionblock',
            name='block_type',
        ),
        migrations.AddField(
            model_name='configblocktype',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configcurrency',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configledgeraccountbalancedirection',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configledgeraccountcategory',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configledgeraccounttype',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configledgertransactionstatus',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configledgertransactiontype',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configledgertype',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ledgeraccountingrule',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='reversing_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.LedgerTransaction'),
        ),
        migrations.AddField(
            model_name='ledgertransactionblock',
            name='ledger_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgertransactionblock',
            name='ledger_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ConfigLedgerType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='ledger_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.LedgerTransaction'),
        ),
        migrations.DeleteModel(
            name='LedgerProductBlockItem',
        ),
    ]
