# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigGLTransactionEntryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_by', models.ForeignKey(db_column=b'created_by', on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounting_configgltransactionentrytype_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column=b'deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounting_configgltransactionentrytype_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_gl_transaction_entry_type',
                'verbose_name': 'Config GL Transaction Entry Type',
            },
        ),
        migrations.AlterModelOptions(
            name='configglaccountcategory',
            options={'verbose_name': 'Config GL Account Category', 'verbose_name_plural': 'Config GL Account Categories'},
        ),
        migrations.AddField(
            model_name='generalledgertransaction',
            name='entry_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financial_accounting.ConfigGLTransactionEntryType'),
            preserve_default=False,
        ),
    ]
