# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounting', '0003_auto_20160218_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalledgertransaction',
            name='gl_account',
        ),
        migrations.AddField(
            model_name='generalledgertransactionentry',
            name='gl_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financial_accounting.GeneralLedgerAccount'),
            preserve_default=False,
        ),
    ]
