# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounting', '0004_auto_20160218_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='configglaccountcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configglaccounttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configgltransactionentrytype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configgltransactionstatus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
