# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounting', '0005_auto_20160221_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configglaccountcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configglaccountcategory',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='configglaccounttype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configglaccounttype',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='configgltransactionentrytype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configgltransactionentrytype',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='configgltransactionstatus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configgltransactionstatus',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='generalledgeraccount',
            name='account_category',
        ),
        migrations.RemoveField(
            model_name='generalledgeraccount',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='generalledgeraccount',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='generalledgeraccount',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='generalledgertransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='generalledgertransaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='generalledgertransaction',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='generalledgertransaction',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='generalledgertransaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='generalledgertransactionentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='generalledgertransactionentry',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='generalledgertransactionentry',
            name='gl_account',
        ),
        migrations.RemoveField(
            model_name='generalledgertransactionentry',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='ConfigGLAccountCategory',
        ),
        migrations.DeleteModel(
            name='ConfigGLAccountType',
        ),
        migrations.DeleteModel(
            name='ConfigGLTransactionEntryType',
        ),
        migrations.DeleteModel(
            name='ConfigGLTransactionStatus',
        ),
        migrations.DeleteModel(
            name='GeneralLedgerAccount',
        ),
        migrations.DeleteModel(
            name='GeneralLedgerTransaction',
        ),
        migrations.DeleteModel(
            name='GeneralLedgerTransactionEntry',
        ),
    ]
