# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('initial', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=140)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_buggy', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'website_cms_module',
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('icon', models.FileField(upload_to='cms/images/')),
                ('description', models.CharField(max_length=140)),
            ],
            options={
                'db_table': 'website_cms_offering',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('secondary_title', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=2000)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'website_cms_page',
            },
        ),
    ]
