# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name (required)')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle Name')),
                ('sur_name', models.CharField(max_length=50, verbose_name='Surname (required)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address (required)')),
                ('mobile_phone_number', models.CharField(max_length=20, verbose_name='Mobile Phone Number (required)')),
                ('channel', models.IntegerField(choices=[(1, 'Local Tradional Media'), (2, 'A Friend'), (3, 'Ajab Capital Marketing'), (4, 'Google'), (5, 'Other')], verbose_name='How did you hear about us? (required)')),
                ('company', models.CharField(max_length=140, verbose_name='Your Company (required)')),
                ('role', models.PositiveIntegerField(choices=[(1, 'Managing Director/CEO'), (2, 'CTO/CIO/IT Director/Manager'), (3, 'Loan Officer/Administrator'), (4, 'Staff'), (5, 'Media')], verbose_name='Your Role (required)')),
                ('enrollment_code', models.CharField(max_length=15, unique=True)),
                ('modules', models.ManyToManyField(to='website.Module')),
            ],
        ),
    ]
