# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='channel',
            field=models.IntegerField(choices=[(1, 'ajab capital marketing'), (2, 'local tradional media'), (3, 'a friend/word of mouth'), (4, 'google'), (5, 'other')], verbose_name='How did you hear about us? (required)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'Business Executive'), (2, 'Technology Executive'), (3, 'Banking/Loan Executive'), (4, 'Media Executive')], verbose_name='Your Role (required)'),
        ),
    ]
