# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configamortizationtype',
            options={'verbose_name': 'Config Amortization Type', 'verbose_name_plural': 'Config Amortization Types'},
        ),
        migrations.AlterModelOptions(
            name='configcurrency',
            options={'verbose_name': 'Config Currency', 'verbose_name_plural': 'Config Currencies'},
        ),
        migrations.AlterModelOptions(
            name='configgraceperiodtype',
            options={'verbose_name': 'Config Grace Period Type', 'verbose_name_plural': 'Config Grace Period Types'},
        ),
        migrations.AlterModelOptions(
            name='configinterestcalculationmethod',
            options={'verbose_name': 'Config Interest Calculation Method', 'verbose_name_plural': 'Config Interest Calculation Methods'},
        ),
        migrations.AlterModelOptions(
            name='configloanaccountstatus',
            options={'verbose_name': 'Config Loan Account Status', 'verbose_name_plural': 'Config Loan Account Statuses'},
        ),
        migrations.AlterModelOptions(
            name='configloanaccounttransactionstatus',
            options={'verbose_name': 'Config Loan Transaction Status', 'verbose_name_plural': 'Config Loan Transaction Statuses'},
        ),
        migrations.AlterModelOptions(
            name='configloanaccounttransactiontype',
            options={'verbose_name': 'Config Loan Transaction Type', 'verbose_name_plural': 'Config Loan Transaction Types'},
        ),
        migrations.AlterModelOptions(
            name='configloanperiodunit',
            options={'verbose_name': 'Config Loan Period Unit', 'verbose_name_plural': 'Config Loan Period Units'},
        ),
        migrations.AlterModelOptions(
            name='configloanproductfeetype',
            options={'verbose_name': 'Config Loan Product Fee Type', 'verbose_name_plural': 'Config Loan Product Fee Types'},
        ),
        migrations.AlterModelOptions(
            name='configloanproducttype',
            options={'verbose_name': 'Config Loan Product Type', 'verbose_name_plural': 'Config Loan Product Types'},
        ),
        migrations.AlterModelOptions(
            name='configpaymentfrequency',
            options={'verbose_name': 'Config Payment Frequency', 'verbose_name_plural': 'Config Payment Frequencies'},
        ),
        migrations.AlterModelOptions(
            name='configtransactiontype',
            options={'verbose_name': 'Config Transaction Type', 'verbose_name_plural': 'Config Transaction Types'},
        ),
        migrations.AddField(
            model_name='configinterestcalculationmethod',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='config/icons/'),
        ),
        migrations.AddField(
            model_name='configloanaccountstatus',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='config/icons/'),
        ),
        migrations.AddField(
            model_name='configloanaccounttransactionstatus',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='config/icons/'),
        ),
        migrations.AddField(
            model_name='configloanaccounttransactiontype',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='config/icons/'),
        ),
        migrations.AddField(
            model_name='configloanproducttype',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='config/icons/'),
        ),
        migrations.AddField(
            model_name='configtransactiontype',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='config/icons/'),
        ),
        migrations.AlterModelTable(
            name='configamortizationtype',
            table='config_amortization_type',
        ),
        migrations.AlterModelTable(
            name='configcurrency',
            table='config_currency',
        ),
        migrations.AlterModelTable(
            name='configgraceperiodtype',
            table='config_grace_period_type',
        ),
        migrations.AlterModelTable(
            name='configinterestcalculationmethod',
            table='config_interest_calculation_method',
        ),
        migrations.AlterModelTable(
            name='configloanaccountstatus',
            table='config_loan_account_status',
        ),
        migrations.AlterModelTable(
            name='configloanaccounttransactionstatus',
            table='config_loan_account_transaction_status',
        ),
        migrations.AlterModelTable(
            name='configloanaccounttransactiontype',
            table='config_loan_account_transaction_type',
        ),
        migrations.AlterModelTable(
            name='configloanperiodunit',
            table='config_loan_period_unit',
        ),
        migrations.AlterModelTable(
            name='configloanproductfeetype',
            table='config_loan_product_fee_type',
        ),
        migrations.AlterModelTable(
            name='configloanproducttype',
            table='config_loan_product_type',
        ),
        migrations.AlterModelTable(
            name='configpaymentfrequency',
            table='config_payment_frequency',
        ),
        migrations.AlterModelTable(
            name='configtransactiontype',
            table='config_transaction_type',
        ),
    ]
