# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0003_auto_20160426_0933'),
        ('loan', '0002_auto_20160426_0929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigLoanRiskClassification',
        ),
    ]
