# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0006_auto_20160426_0954'),
        ('loan', '0003_delete_configloanriskclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='current_risk_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_management.ConfigLoanRiskClassification'),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='current_risk_classification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
