# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_auto_20160216_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanledgeraccount',
            name='ll_code',
        ),
    ]
