# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_remove_loanledgeraccount_ll_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanproductfundsource',
            old_name='fund_source_account',
            new_name='base_account',
        ),
        migrations.AddField(
            model_name='loanproductfundsource',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
