# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:58
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0007_auto_20160216_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigFeeCalculationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_by', models.ForeignKey(db_column=b'created_by', on_delete=django.db.models.deletion.CASCADE, related_name='loan_configfeecalculationmethod_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column=b'deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_configfeecalculationmethod_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_fee_calculation_method',
                'verbose_name': 'Config Fee Calculation Method',
            },
        ),
        migrations.RemoveField(
            model_name='loanproductfee',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loanproductfee',
            name='currency',
        ),
        migrations.AddField(
            model_name='loanproductfee',
            name='flat_fee_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='loanproductfee',
            name='flat_fee_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigCurrency'),
        ),
        migrations.AddField(
            model_name='loanproductfee',
            name='percentage_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='loanaccounttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='loanaccounttransactionentry',
            name='ledger_balance_increment',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='default_interest_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='max_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='max_interest_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='min_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='min_interest_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='loanproductfee',
            name='fee_calculation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigFeeCalculationMethod'),
            preserve_default=False,
        ),
    ]
