# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 06:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0010_auto_20160217_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigRepaymentAllocationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_by', models.ForeignKey(db_column=b'created_by', on_delete=django.db.models.deletion.CASCADE, related_name='loan_configrepaymentallocationitem_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column=b'deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_configrepaymentallocationitem_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_repayment_allocation_item',
            },
        ),
        migrations.CreateModel(
            name='LoanRepaymentAllocationOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField()),
                ('allocation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentAllocationItem')),
                ('created_by', models.ForeignKey(db_column=b'created_by', on_delete=django.db.models.deletion.CASCADE, related_name='loan_loanrepaymentallocationorder_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column=b'deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_loanrepaymentallocationorder_deleted_by_me', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.LoanProduct')),
            ],
            options={
                'db_table': 'loan_repayment_allocation_order',
                'verbose_name': 'Loan Repayment Allocation Order',
            },
        ),
        migrations.AlterModelOptions(
            name='loanproductcontrolaccount',
            options={'verbose_name': 'Loan Product Control'},
        ),
        migrations.RemoveField(
            model_name='loanprofile',
            name='has_current_delinquency',
        ),
        migrations.RemoveField(
            model_name='loanprofile',
            name='has_historical_delinquency',
        ),
        migrations.RemoveField(
            model_name='loanprofile',
            name='is_performing',
        ),
        migrations.RemoveField(
            model_name='loanprofile',
            name='max_days_in_arrears',
        ),
        migrations.RemoveField(
            model_name='loanprofile',
            name='min_days_in_arrears',
        ),
        migrations.RemoveField(
            model_name='loanprofile',
            name='no_of_requests',
        ),
        migrations.AddField(
            model_name='loanaccounttransaction',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigCurrency'),
        ),
    ]
