# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_auto_20160218_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configloanpipelinestep',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configloanpipelinestep',
            name='deleted_by',
        ),
        migrations.DeleteModel(
            name='ConfigLoanPipelineStep',
        ),
    ]
