# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 15:42
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_auto_20160218_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='configloanriskclassification',
            name='default_provision',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6),
        ),
    ]
