# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_configloanriskclassification_default_provision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configcurrency',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configcurrency',
            name='deleted_by',
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ConfigCurrency'),
        ),
        migrations.AlterField(
            model_name='loanaccounttransaction',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ConfigCurrency'),
        ),
        migrations.AlterField(
            model_name='loanproductfee',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ConfigCurrency'),
        ),
        migrations.DeleteModel(
            name='ConfigCurrency',
        ),
    ]
