# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('loan', '0015_auto_20160218_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanaccounttransaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='loanproductfee',
            name='currency',
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ConfigCurrency'),
        ),
    ]
