# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 23:24
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
        ('loan', '0017_auto_20160218_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18)),
                ('notified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column=b'created_by', on_delete=django.db.models.deletion.CASCADE, related_name='loan_loantransaction_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column=b'deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_loantransaction_deleted_by_me', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loan.ConfigLoanAccountTransactionStatus')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigLoanTransactionType')),
            ],
            options={
                'db_table': 'loan_transaction',
                'verbose_name': 'Loan Account Transaction',
            },
        ),
        migrations.RemoveField(
            model_name='loanaccounttransaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='loanaccounttransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loanaccounttransaction',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='loanaccounttransaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='loanaccounttransaction',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='loanaccounttransactionentry',
            name='ledger_account',
        ),
        migrations.RemoveField(
            model_name='loanprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='loanaccounttransactionentry',
            name='loan_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loan.LoanAccount'),
        ),
        migrations.AddField(
            model_name='loanaccounttransactionentry',
            name='loan_ledger_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loan.LoanLedgerAccount'),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='customer_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.CustomerProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanaccounttransactionentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='loan.LoanTransaction'),
        ),
        migrations.AlterField(
            model_name='loanledgeraccount',
            name='gl_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='LoanAccountTransaction',
        ),
    ]
