# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 00:00
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0002_auto_20160219_0000'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0018_auto_20160218_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigLoanRiskLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('default_provision', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('icon', models.FileField(blank=True, null=True, upload_to='config/icons/')),
                ('created_by', models.ForeignKey(db_column=b'created_by', on_delete=django.db.models.deletion.CASCADE, related_name='loan_configloanrisklevel_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column=b'deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_configloanrisklevel_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_loan_risk_level',
                'verbose_name': 'Config Loan Risk Level',
            },
        ),
        migrations.RemoveField(
            model_name='configloanriskclassification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configloanriskclassification',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='risk_classification',
        ),
        migrations.DeleteModel(
            name='ConfigLoanRiskClassification',
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='risk_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigLoanRiskLevel'),
            preserve_default=False,
        ),
    ]
