# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 07:48
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0020_auto_20160219_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configloanrisklevel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configloanrisklevel',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='risk_level',
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='risk_classification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigLoanRiskClassification'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConfigLoanRiskLevel',
        ),
    ]
