# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0024_auto_20160221_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='amount_currency',
            field=models.ForeignKey(db_column='currency', default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ConfigCurrency'),
            preserve_default=False,
        ),
    ]
