# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0026_auto_20160221_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanproduct',
            name='amount_currency',
        ),
    ]
