# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0030_auto_20160221_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configpaymentfrequency',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configpaymentfrequency',
            name='deleted_by',
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='default_repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.DeleteModel(
            name='ConfigPaymentFrequency',
        ),
    ]
