# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0031_auto_20160221_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanproduct',
            name='default_grace_period',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='default_grace_period_unit',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='grace_period_type',
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='default_repayment_grace_period',
            field=models.IntegerField(blank=True, db_column='default_grace_period', null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='default_repayment_grace_period_unit',
            field=models.ForeignKey(blank=True, db_column='default_grace_period_unit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grace_products', to='loan.ConfigLoanPeriodUnit'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='repayment_grace_period_type',
            field=models.ForeignKey(blank=True, db_column='grace_period_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigGracePeriodType'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='default_repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
    ]
