# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0043_auto_20160222_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configamortizationtype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configamortizationtype',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='amortization_type',
        ),
        migrations.AlterField(
            model_name='configloanperiodunit',
            name='frequencies',
            field=models.ManyToManyField(to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='grace_period',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='grace_period_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grace_periods', to='loan.ConfigLoanPeriodUnit'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='last_current_balance_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='last_disbursal_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='last_overdue_balance_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='last_repayment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='default_repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.DeleteModel(
            name='ConfigAmortizationType',
        ),
    ]
