# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_auto_20160229_0743'),
        ('loan', '0051_auto_20160228_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanChartOfAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='loan_loanchartofaccounts_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_loanchartofaccounts_deleted_by_me', to=settings.AUTH_USER_MODEL)),
                ('loan_fee_income_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_fee_income', to='core.LedgerAccount')),
                ('loan_fee_income_receivable_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_fee_receivable', to='core.LedgerAccount')),
                ('loan_fee_write_off_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_fee_writeoff', to='core.LedgerAccount')),
                ('loan_funding_source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_funding', to='core.LedgerAccount')),
                ('loan_interest_income_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_interest_income', to='core.LedgerAccount')),
                ('loan_interest_income_receivable_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_interest_receivable', to='core.LedgerAccount')),
                ('loan_interest_write_off_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_interest_writeoff', to='core.LedgerAccount')),
                ('loan_penalty_income_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_penalty_income', to='core.LedgerAccount')),
                ('loan_penalty_income_receivable_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_penalty_receivable', to='core.LedgerAccount')),
                ('loan_penalty_write_off_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_penalty_writeoff', to='core.LedgerAccount')),
                ('loan_portfolio_control_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_portfolio', to='core.LedgerAccount')),
                ('loan_principal_write_off_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_principal_writeoff', to='core.LedgerAccount')),
            ],
            options={
                'db_table': 'loan_chart_of_accounts',
            },
        ),
        migrations.RemoveField(
            model_name='loanproductcontrolaccount',
            name='base_account',
        ),
        migrations.RemoveField(
            model_name='loanproductcontrolaccount',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loanproductcontrolaccount',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='loanproductcontrolaccount',
            name='product',
        ),
        migrations.RemoveField(
            model_name='loanproductfundsource',
            name='base_account',
        ),
        migrations.RemoveField(
            model_name='loantransactionregister',
            name='loan_account',
        ),
        migrations.AlterField(
            model_name='configloanperiodunit',
            name='frequencies',
            field=models.ManyToManyField(to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='default_repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.DeleteModel(
            name='LoanProductControlAccount',
        ),
    ]
