# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0052_auto_20160229_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanaccount',
            old_name='last_accrual_amount',
            new_name='last_accrual_balance',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='currency',
            new_name='loan_amount_currency',
        ),
        migrations.AlterField(
            model_name='configloanperiodunit',
            name='frequencies',
            field=models.ManyToManyField(to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='default_repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
    ]
