# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 11:29
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_auto_20160307_1129'),
        ('loan', '0053_auto_20160229_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAccountBlock',
            fields=[
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=160)),
                ('ledger_id', models.IntegerField(null=True)),
                ('balances_as_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='loan_loanaccountblock_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_loanaccountblock_deleted_by_me', to=settings.AUTH_USER_MODEL)),
                ('ledger_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ConfigLedgerType')),
            ],
            options={
                'db_table': 'loan_account_transaction_block',
                'verbose_name': 'Loan Account Block',
            },
        ),
        migrations.CreateModel(
            name='LoanAccountBlockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_items', to='loan.LoanAccountBlock')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='loan_loanaccountblockitem_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_loanaccountblockitem_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_account_transaction_block_item',
                'verbose_name': 'Loan Account Block Item',
            },
        ),
        migrations.CreateModel(
            name='LoanProductBlock',
            fields=[
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=160)),
                ('ledger_id', models.IntegerField(null=True)),
                ('balances_as_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='loan_loanproductblock_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_loanproductblock_deleted_by_me', to=settings.AUTH_USER_MODEL)),
                ('ledger_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ConfigLedgerType')),
            ],
            options={
                'db_table': 'loan_product_transaction_block',
                'verbose_name': 'Loan Product Block',
            },
        ),
        migrations.CreateModel(
            name='LoanProductBlockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_items', to='loan.LoanProductBlock')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='loan_loanproductblockitem_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_loanproductblockitem_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_product_transaction_block_item',
                'verbose_name': 'Loan Product Block Item',
            },
        ),
        migrations.RemoveField(
            model_name='loantransactionregister',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loantransactionregister',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='loantransactionregister',
            name='transaction',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='last_disbursal_date',
            new_name='loan_amount_disbursal_date',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='last_disbursal_amount',
        ),
        migrations.AddField(
            model_name='configfeecalculationmethod',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configgraceperiodtype',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configinterestcalculationmethod',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configloanaccountstatus',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configloangrouprole',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configloangroupstatus',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configloanperiodunit',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configloanproductfeetype',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configloanproducttype',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configloanriskclassification',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configrepaymentallocationitem',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configrepaymentfrequency',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='loan_rescheduled',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.LoanAccount'),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='loan_rescheduled_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='configloanperiodunit',
            name='frequencies',
            field=models.ManyToManyField(to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='default_repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.DeleteModel(
            name='LoanTransactionRegister',
        ),
        migrations.AddField(
            model_name='loanaccountblockitem',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.LoanAccount'),
        ),
    ]
