# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0055_auto_20160307_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanaccount',
            old_name='loan_rescheduled_date',
            new_name='last_account_status_date',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='loan_rescheduled',
            new_name='loan_restructured',
        ),
        migrations.RenameField(
            model_name='loanproduct',
            old_name='loan_type',
            new_name='product_type',
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='last_account_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigLoanAccountStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='loan_restructured_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='configloanperiodunit',
            name='frequencies',
            field=models.ManyToManyField(to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='default_repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanprofile',
            name='no_of_closed_loans',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loanprofile',
            name='no_of_current_loans',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loanprofile',
            name='no_of_loans',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
