# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 01:32
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160307_1129'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0009_auto_20160323_0132'),
        ('loan', '0057_auto_20160322_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18)),
                ('loan_amount_disbursal_date', models.DateTimeField(null=True)),
                ('terms_restructured_date', models.DateTimeField(null=True)),
                ('repayment_period', models.IntegerField()),
                ('grace_period', models.IntegerField(null=True)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=6)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='loan_loanterm_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_loanterm_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_term',
                'verbose_name': 'Loan Term',
            },
        ),
        migrations.RemoveField(
            model_name='configloangrouprole',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configloangrouprole',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='configloangroupstatus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='configloangroupstatus',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='loangroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loangroup',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='loangroupstatus',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='loangroupstatus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loangroupstatus',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='loangroupstatus',
            name='group',
        ),
        migrations.RemoveField(
            model_name='loangroupstatus',
            name='status',
        ),
        migrations.RemoveField(
            model_name='loanprofilegroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loanprofilegroup',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='loanprofilegroup',
            name='group_role',
        ),
        migrations.RemoveField(
            model_name='loanprofilegroup',
            name='loan_group',
        ),
        migrations.RemoveField(
            model_name='loanprofilegroup',
            name='loan_profile',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='last_accrual_date',
            new_name='last_accruals_date',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='last_accrual_balance',
            new_name='last_fees_overdue',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='last_overdue_balance_date',
            new_name='last_fees_overdue_date',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='grace_period',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='grace_period_unit',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='last_overdue_balance',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='loan_amount_currency',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='loan_amount_disbursal_date',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='loan_profile_group',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='loan_restructured',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='loan_restructured_date',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='repayment_frequency',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='repayment_period',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='repayment_period_unit',
        ),
        migrations.RemoveField(
            model_name='loanprofile',
            name='customer_profile',
        ),
        migrations.RemoveField(
            model_name='loanprofile',
            name='first_disbursal',
        ),
        migrations.RemoveField(
            model_name='loanprofile',
            name='last_repayment',
        ),
        migrations.RemoveField(
            model_name='loanprofile',
            name='no_of_closed_loans',
        ),
        migrations.RemoveField(
            model_name='loanprofile',
            name='no_of_current_loans',
        ),
        migrations.RemoveField(
            model_name='loanprofile',
            name='no_of_loans',
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='last_principal_overdue',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='last_principal_overdue_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='business_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.BusinessProfile'),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='group_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.GroupProfile'),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='individual_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.IndividualProfile'),
        ),
        migrations.AlterField(
            model_name='configloanperiodunit',
            name='frequencies',
            field=models.ManyToManyField(to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='last_repayment_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='loan_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.LoanProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='default_repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanprofile',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.DeleteModel(
            name='ConfigLoanGroupRole',
        ),
        migrations.DeleteModel(
            name='ConfigLoanGroupStatus',
        ),
        migrations.DeleteModel(
            name='LoanGroup',
        ),
        migrations.DeleteModel(
            name='LoanGroupStatus',
        ),
        migrations.DeleteModel(
            name='LoanProfileGroup',
        ),
        migrations.AddField(
            model_name='loanterm',
            name='grace_period_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grace_periods', to='loan.ConfigLoanPeriodUnit'),
        ),
        migrations.AddField(
            model_name='loanterm',
            name='loan_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='loan.LoanAccount'),
        ),
        migrations.AddField(
            model_name='loanterm',
            name='loan_amount_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ConfigCurrency'),
        ),
        migrations.AddField(
            model_name='loanterm',
            name='repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AddField(
            model_name='loanterm',
            name='repayment_period_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loan.ConfigLoanPeriodUnit'),
        ),
        migrations.AddField(
            model_name='loanterm',
            name='terms_restructured',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.LoanTerm'),
        ),
    ]
