# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0074_auto_20160323_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='loan_fund',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='loan.LoanFund'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='product_channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigLoanProductChannel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configloanperiodunit',
            name='frequencies',
            field=models.ManyToManyField(to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='default_repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanterm',
            name='repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
    ]
