# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 15:02
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0075_auto_20160323_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanproductfundsource',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loanproductfundsource',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='loanproductfundsource',
            name='product',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='last_account_status',
            new_name='current_account_status',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='last_account_status_date',
            new_name='current_account_status_date',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='last_current_balance',
            new_name='current_balance',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='last_current_balance_date',
            new_name='current_balance_date',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='last_fees_overdue',
            new_name='fees_accrued',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='last_fees_overdue_date',
            new_name='next_accruals_date',
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='last_principal_overdue',
            new_name='principal_accrued',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='last_principal_overdue_date',
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='next_repayment_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='next_repayment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='penalties_accrued',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='configloanperiodunit',
            name='frequencies',
            field=models.ManyToManyField(to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='default_repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanterm',
            name='loan_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', related_query_name='term', to='loan.LoanAccount'),
        ),
        migrations.AlterField(
            model_name='loanterm',
            name='repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanterm',
            name='repayment_period',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='LoanProductFundSource',
        ),
    ]
