# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 08:36
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0076_auto_20160324_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigRepaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system_defined', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='loan_configrepaymentmodel_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_configrepaymentmodel_deleted_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_repayment_model',
                'verbose_name': 'Config Repayment Model',
            },
        ),
        migrations.RenameField(
            model_name='loanaccount',
            old_name='principal_accrued',
            new_name='interest_accrued',
        ),
        migrations.RemoveField(
            model_name='loanfund',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='loanfund',
            name='credit_limit_per_loan',
        ),
        migrations.RemoveField(
            model_name='loanprofile',
            name='business_profile',
        ),
        migrations.RemoveField(
            model_name='loanprofile',
            name='group_profile',
        ),
        migrations.RemoveField(
            model_name='loanprofile',
            name='individual_profile',
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='fund_credit_limit',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='loan_credit_limit',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='principal_overdue',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='product_channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigLoanProductChannel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configloanperiodunit',
            name='frequencies',
            field=models.ManyToManyField(to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='default_repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanterm',
            name='repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='repayment_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentModel'),
            preserve_default=False,
        ),
    ]
