# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0077_auto_20160327_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanfund',
            name='fund_credit_limit',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='loanfund',
            name='loan_credit_limit',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='loanfund',
            name='product_channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigLoanProductChannel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanfund',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigLoanProductType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanfund',
            name='repayment_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configloanperiodunit',
            name='frequencies',
            field=models.ManyToManyField(to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='default_repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanterm',
            name='repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
    ]
