# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20160323_1747'),
        ('loan', '0079_auto_20160327_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanfund',
            name='profile_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigProfileType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='business_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.BusinessProfile'),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='group_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.GroupProfile'),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='individual_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.IndividualProfile'),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='profile_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigProfileType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configloanperiodunit',
            name='frequencies',
            field=models.ManyToManyField(to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='default_repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanterm',
            name='repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
    ]
