# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0081_auto_20160327_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanaccount',
            name='fund_credit_limit',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='loan_credit_limit',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='product_channel',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='repayment_model',
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='repayment_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configloanperiodunit',
            name='frequencies',
            field=models.ManyToManyField(to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='default_repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanterm',
            name='repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
    ]
