# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0083_auto_20160328_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRiskClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('reason_deleted', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=140, null=True)),
            ],
            options={
                'db_table': 'loan_risk_status',
                'verbose_name': 'Loan Risk Classification',
                'verbose_name_plural': 'Loan Risk Classification',
            },
        ),
        migrations.AlterField(
            model_name='configloanperiodunit',
            name='frequencies',
            field=models.ManyToManyField(to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='risk_classification',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigLoanRiskClassification'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='default_repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', default=1, on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AlterField(
            model_name='loanterm',
            name='repayment_frequency',
            field=models.ForeignKey(db_column='payment_frequency', on_delete=django.db.models.deletion.CASCADE, to='loan.ConfigRepaymentFrequency'),
        ),
        migrations.AddField(
            model_name='loanriskclassification',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_classifications', to='loan.LoanAccount'),
        ),
        migrations.AddField(
            model_name='loanriskclassification',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals_on_loan_risk_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanriskclassification',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='loan.ConfigLoanRiskClassification'),
        ),
        migrations.AddField(
            model_name='loanriskclassification',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='loan_loanriskclassification_created_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanriskclassification',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_loanriskclassification_deleted_by_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
